export class Career {
 constructor(page) {}
 IconName= '["icon-menu"]'
 headerVacansies = '.header__vacansies'
 allWaysDropdown = '.select-css--medium:nth-child(1)'
 showVacanciesButton= '[href="https://rozetka.com.ua/ua/careers/catalog/department=9"]'
 allCategories = '.select-css--medium:nth-child(2)'
 allTowns = '.select-css--medium:nth-child(3)'
 displayAll= '[href="https://rozetka.com.ua/ua/careers/catalog/department=9"]'
 partWorking = '[id="Часткова зайнятість"]'
 withoutExperience = '[id="Без досвіду роботи"]'
 nightWorking= '[id="Нічна зміна"]'
 remoteWork= '[id="Віддалена робота"]'
 retailTrade = '[href="https://rozetka.com.ua/ua/careers/department/9"]'
 office = '[href="https://rozetka.com.ua/ua/careers/catalog/department=65"]'
 logistics = '[href="https://rozetka.com.ua/ua/careers/department/11"]'
 it = '[href="https://rozetka.com.ua/ua/careers/department/17"]'
 marketing = '[href="https://rozetka.com.ua/ua/careers/catalog/department=19"]'
 careerCard1 = '.careers-card:nth-child(1)'
 careersPosterImgBlack = '[src="https://xl-static.rozetka.com.ua/assets/img/design/careers/store.png"]'
careersPosterContent = '.careers-poster__content'
careerChip = '.careers-chip: nth-child(1)'
careersMainValues= '[class="careers-main-values-mission__values"]'
careersCompanyLifeImg = '[src="https://content2.rozetka.com.ua/files/images/original/526088320.jpg"]'
careersPathSuccessTitle= '[class="careers-path-success__title"]'
сareersЗathІuccessCardImg = '[src="https://content.rozetka.com.ua/files/images/original/550249328.jpg"]'
careersPathSuccess ='[class="careers-path-success"]'
}
