export class Homepage {
 constructor(page) {}
 phoneInput = '[inputmode="tel"]'
 searchFormSubmit = '.search-form__submit'
 searchFormInput = '.search-form__input'
 submitPhone = '[data-qaid="submit-phone"]'
 iconMenu = '[rziconname="icon-user-simple"]'
 iconHeaderBasket = '[rziconname="icon-header-basket"]'
 elementOnHomepage = '[class="item"]'
 loginIcon = '[rziconname="icon-user-simple"]'
 codeStep = '[data-qaid="code-step"]'
 categoryGoods = '.big-image-theme .content'
//  '[data-testid="category_goods"] .content'
searchNothing = '[class="search-nothing"]'
searchNothingChangeButton = '.button--medium'
sortingDropdown = '.setting-sorting font-rozetka'
headerCatalog = '[data-testid="fat_menu_btn"]'
asusLink='[href="https://rozetka.com.ua/ua/notebooks/c80004/producer=asus/"]'
asusCheckbox = '[class="checkbox-filter-link text-base pointer hover:color-green checkbox-filter-link--checked"]'
}
